version: '3'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        hostname: nginx-proxy
        volumes: 
            - /etc/nginx/certs
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 443:443
            - "80:80" 
        networks:
            - proxy-net

    nginx-proxy-letsencrypt: 
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-proxy-letsencrypt
        volumes_from: 
            - nginx-proxy
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment: 
            - DEFAULT_EMAIL=ncminh@korinno.com
        networks: 
            - proxy-net

    nestjs-app:
        build:
          context: ../nest-app
        container_name: nestjs-app
        hostname: nestjs-app
        ports:
            - "3000:3000" 
        depends_on:
            - nginx-proxy-letsencrypt
        environment: 
            - VIRTUAL_PORT=3000
            - VIRTUAL_HOST=api.korinno.com
            - LETSENCRYPT_HOST=api.korinno.com
            - LETSENCRYPT_EMAIL=ncminh@korinno.com
        networks:
            - proxy-net  
networks:
  proxy-net:

   