version: '3'

services:
    nodejs-app:
        build:
          context: ./nest-app
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "3000:3000" 
        networks:
            - example-net  
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - 443:443
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
  example-net:
    external: true
    